#!/usr/bin/perl
# vim: set ai sw=4 :
use File::Glob qw(:globally :nocase);
use File::Basename;
use Data::Dumper;
use Getopt::Long;

sub print_help();

$DEBUG=0;
$confbase="/opt/local/etc/macports";

## Check command line options

GetOptions(
    "port|p=s"		=> \$specific,
    "manifest|m=s"	=> \$manifest,
    "debug|d"		=> \$DEBUG,
    "bundle-pkgs"	=> \$enable_bundle_pkgs,
    "dry-run|n"		=> \$dryrun,
) or print_help();

$osversion=`sw_vers -productVersion`;
chomp($osversion);
@os_version=split(/\./, $osversion);
$BASE=sprintf("ports%d%d", $os_version[0], $os_version[1]);
printf("Port base is '%s'\n", $BASE) if ($DEBUG);

# Read the macports configuration
my %mpconfig=();
open(MPCONF, "<$confbase/macports.conf") or die ("Can't read macports config file!\n");
while (my $confline = <MPCONF>) {
    next unless ($confline =~/^[a-z]/);
    ($key, $value) = split(/\s+/, $confline);
    $mpconfig{$key} = $value;
    printf("Config read: %s is %s\n", $key, $value) if ($DEBUG);
}
if ($mpconfig{'package.flat'} eq 'yes') {
    print("Good - package.flat is set to yes.\n") if ($DEBUG);
} elsif (! defined($enable_bundle_pkgs) ) {
    my $helptext = << 'EOH';
WARNING: MacPorts should be configured to build flat packages!
Building non-flat (bundle) pkgs requires munkiimport to wrap your
pkg file in a DMG which is slower and can trigger issues building
large DMGs.

If you *really* want to continue building DMG-wrapped pkg bundles,
add --bundle-pkgs to your command line.
EOH
    print($helptext);
    exit (1);
}


# Read from munkiimport configuration
$mi_repo=`defaults read com.googlecode.munki.munkiimport.plist repo_path 2>/dev/null`;
chomp($mi_repo);
if ($mi_repo eq '' ) {
    print("Error: No Munki repo configured for munkiimport!\n");
    print("You must run munkiimport --configure first.\n");
    exit (1);
}
if (! -d $mi_repo) {
    printf("Error: Munki repo %s not found!\n", $mi_repo);
    print("Do you need to mount your Munki repo?\n");
    exit (1);
} else {
    $munki_repo=$mi_repo;
    $INFOS=sprintf("%s/pkgsinfo/%s", $munki_repo, $BASE);
    printf ("Using pkginfos in %s\n", $INFOS) if ($DEBUG)
}

# Safety checks for writing a manifest
if ($manifest) {
    # Is the manifest a name or a file path?
    ($manifest_name, $manifest_path)=fileparse($manifest);
    if ($manifest_path eq './') {
	# No path given - assuming name not path
	$manifest_file="$munki_repo/manifests/$manifest_name";
    } else {
    	# Full path given
	$manifest_file="$manifest_path/$manifest_file";
    }

    if (! -f "$manifest_file") {
    	# Create new manifest
	$jobout=system("/usr/local/munki/manifestutil new-manifest $manifest_file");
	if ($jobout != 0) {
	    die ("Unable to create new manifest $manifest_file!");
	}
    }
}

## Check to repack only specific port
if ($specific && $specific ne '') {
    print "Importing port $specific\n";
    open(PORTLIST, "/opt/local/bin/port installed 2>/dev/null | grep '^ *$specific ' |")
	or die "Can't list port $specific\n";
} else {
    open(PORTLIST, "/opt/local/bin/port installed 2>/dev/null | /usr/bin/sed -e '1d' |")
	or die "Can't list ports\n";
}

open(MANIFEST, ">/tmp/import-manifest" ) || die ("Can't write manifest\n");

# List of packages imported
@packages=();

while (<PORTLIST>) {
    chomp();
    next unless (/\(active\)$/);
    ($portname, $portmeta)=split();
    ($ver, @variants)=split(/\+/, $portmeta);
    $ver=~s/^\@(.*)_.*/\1/;

    # Fix package names that contain things that Munki mistakes
    #	for version numbers
    ($munkiname=$portname)=~s/-([0-9])/_\1/g;

    # Move on if munki already has this port
    $pkginfo_file="$INFOS/$munkiname-$ver.plist";
    printf("Checking for pkginfo %s...\n", $pkginfo_file) if ($DEBUG);
    if (-f "$INFOS/$munkiname-$ver.plist") {
	print "INFO: pkg $portname seems to exist in munki already - skipping\n";
	next;
    }

    # Determine dependencies
    @libdeps=(); @rundeps=();
    open(DEP, "port deps $portname 2>/dev/null|");
    while(<DEP>) {
       chomp();
       if (/^Library Dependencies/) {
	    $_=~s/Library Dependencies: //;
	    @libdeps=split(', ');
       }
       if (/^Runtime Dependencies/) {
	    $_=~s/Runtime Dependencies: //;
	    @rundeps=split(', ');
       }
    }

    print "$portname (v $ver)\n";
    next if ($dryrun);
    $portwork=`port work $portname 2>/dev/null`;
    chomp($portwork);
    if (length($portwork)<2) {
	# No workdir, so no pkg - might have been cleaned
	$ret=build_port_pkg($portname, \@variants);
	$portwork=`port work $portname 2>/dev/null`;
	chomp($portwork);
	die("No work directory for $portname!\n") if(length($portwork)<2);
    }
    $portpkg=find_port_pkg($portname);
    if(length($portpkg)<2) {
        build_port_pkg($portname, \@variants);
	$portpkg=find_port_pkg($portname);
	die("Can't build pkg for $portname!\n") if (length($portpkg)<2);
    }

    $minver=sprintf("%d.%d.0", $os_version[0], $os_version[1]);
    $maxver=sprintf("%d.%d.99", $os_version[0], $os_version[1]);
    $importargs="--name=$munkiname --pkgvers=$ver --subdirectory $BASE --unattended_install";
    $importargs.=" --minimum_os_version=$minver --maximum_os_version=$maxver";
    foreach $dep (@libdeps, @rundeps) {
	$dep=~s/-([0-9])/_\1/;
	$importargs.=" -r $dep";
    }
    # Find files to take md5 sum for
    @fileslist=find_port_files($portname);
    foreach $portfile (@fileslist) {
    	# Add md5sum for the binary
	$importargs.=" -f $portfile";
    }
    print "DBG- import arguments: $importargs\n" if ($DEBUG);
    if (-f "$PKGS/$portname-$portver.dmg" ) {
	# DMG exists, just re-generate metadata
	$jobout=system("/usr/local/munki/makepkginfo $importargs $portpkg > $INFOS/$portname-$portver.plist");
    } else {
	$jobout=system("/usr/local/munki/munkiimport -n $importargs $portpkg");
    }
    die("munkiimport failed!\n") if ($jobout>0);
    push (@packages, $munkiname);

    # Add packages to the configured manifest
    printf MANIFEST "\t\t<string>%s</string>\n", $munkiname;
    if ($manifest_file) {
	$jobout=system("/usr/local/munki/manifestutil add-pkg $munkiname --manifest $manifest_file");
    }
}


###################################################################################

sub build_port_pkg ($@) {
	my $portname=$_[0];
	my @variants=@{$_[1]};
	print "  Building pkg for $portname...\n";
	$pkgopts=join(' +', @variants);
	print "DBG: port pkg $portname +$pkgopts\n";
	$pbuildstr="sudo port pkg $portname";
	if($pkgopts) {
	    $pbuildstr.=" +$pkgopts";
	}
	print "DBG: build pkg: $pbuildstr\n" if ($DEBUG>0);
	system($pbuildstr);
	return $?;
}

sub find_port_pkg ($) {
    my $portname=$_[0];

    $portwork=`port work $portname 2>/dev/null`;
    chomp($portwork);
    if(length($portwork)<2) {
    	return('');
    }
    @files=glob("$portwork/$portname*pkg");
    $pkgfile='';
    foreach $try (@files) {
        next if ($try=~/-component/);
	$pkgfile=$try;
    }
    if ( -e $pkgfile ) {
	print "Found pkg for $portname\n";
	return($pkgfile);
    } else {
	return('');
    }
}

sub find_port_files ($) {
    my $portname=$_[0];
    my $numlib=0;
    my $numbin=0;
    my $libargs='';
    my $binargs='';
    my @portfiles=();
    open (PF, "port contents $portname|") or die ("Can't list port contents for $portname\n");
    while (my $file=<PF>) {
	chomp($file);
	$file=~s/^ *//;
	next unless (-f $file);
    	if ($file=~/local\/bin\//) {
	    $numbin++;
	    next if($numbin > 2);	# Keep the installs array to reasonable size
	    push (@portfiles, $file);
	}
        if ($file=~/Python.framework.*egg-info/) {
            $numlib++;
            next if($numlib > 2);
            push (@portfiles, $file);
        }
	if ($file=~/local\/lib\/.*dylib/) {
	    $numlib++;
	    next if($numlib > 2);
	    push (@portfiles, $file);
	}
    }
    return (@portfiles);
}

########################

sub print_help () {

    my $helptext = << "EOH";
Usage: import-macports [options]

    -p|--port		Import only this port (default is to import all active ports)
    -m|--manifest	Add imported ports to this manifest file (full path)
    -d|--debug          Print verbose debugging info

EOH
    print ($helptext);
    exit 1;
}
